### PR TITLE
More reliable serial read from PM2.5 sensor.

### PR DESCRIPTION
**Pull request by tomcpierce**
- **Describe the scope of your change--i.e. what the change does and what parts
  of the code were modified.**  This will help us understand any risks of integrating
  the code.

This changes serial reads from the PM2.5 sensor to scan buffered input (up to one
message's worth of bytes), looking for the header byte.  It bails out if no data is available, or
after the magic start byte isn't found within a message's worth of bytes, to avoid 
hanging.  Depending on the delays callers add between read attempts, this can reduce
 failed reads significantly

- **Describe any known limitations with your change.**  For example if the change
  doesn't apply to a supported platform of the library please mention it.

The modified version should work on any platform - it will probably make the biggest
difference on devices with limited buffering and/or software serial (I see big differences
in read-failure rates using software serial on a HUZZAH ESP8266).

- **Please run any tests or examples that can exercise your modified code.**  We
  strive to not break users of the code and running tests/examples helps with this
  process.

I have run the test program (as well as my own), and I see much more reliable reads with the 
changed version.

### CODE REVIEW

**Comment by ladyada** [comment]
hihi looks neat, can you re-write it as a while loop? the for construct seems a bit harder to read in this case

**Comment by tomcpierce** [comment]
Done.

**Comment by ladyada** [comment]
tested with a qt py!

**Comment by ladyada** [comment]
thanks :)

**Pull request merged**
