### PR TITLE
Add compatability and auto-detection for the Cubic PM1006 air quality sensor

### PR DESCRIPTION
**Pull request by brentru**
This pull request adds compatibility for this library to work with the Cubic PM1006 LED Particle Sensor. This sensor is used in the IKEA VINDSTRYKKA.
* Adds auto-detection for start-bytes to differentiate between the sensors
* Modifies `Adafruit_PM25AQI::read()` to work with Adafruit's Air Quality Sensors or the Cubic PM1006
* Added a demo sketch, `PM1006_test.ino`, to show usage
* Note that this sensor doesn't have I2C and can only read PM 25 Environmental values. As a result, it can't write into all the members of the `PM25_AQI_Data` struct. Therefore, only the checksum and `pm25_env` values are written into this struct.

Tested on hardware with:
* "Hacked"  IKEA VINDSTRYKKA connected to an Adafruit QTPY ESP32 over UART
  * Using `PM1006_test.ino` sketch
* Feather ESP32-S3 connected to a [PM2.5 Air Quality Sensor and Breadboard Adapter Kit - PMS5003](https://www.adafruit.com/product/3686) over UART. 
  * Using `pm25_test.ino` sketch.

### CODE REVIEW

**Comment by tyeth** [comment]
Tested on metro-s2, it was not behaving as I'd expect (with no prior knowledge), the Ikea board appears to ask the sensor for 5 readings and then sleeps for 20seconds before another set of readings. As we are just passively monitoring this sensor rather than initiating readings I think this is the best we can hope for.
Added prints (was hoping to peek at bad bytes), but it was just serial unavailable during those times which I guess is fair enough.

**Comment by brentru** [comment]
> the Ikea board appears to ask the sensor for 5 readings and then sleeps for 20seconds before another set of readings. As we are just passively monitoring this sensor rather than initiating readings I think this is the best we can hope for.

Yeah, the sleep period of the sketch in the demo (https://github.com/Hypfer/esp8266-vindriktning-particle-sensor) was 30 seconds. We could sleep for this duration but the actual code is monitoring the sensor as readings are initiated by the MCU on the ikea sensor's mainboard.

**Comment by brentru** [comment]
After discussing with @tyeth  on slack, I've changed the sampling interval to every 5 seconds. We also now wait 20 seconds between successful reads.

**Comment by caternuson** [comment]
Did not test, but LGTM.

**Review by caternuson — APPROVED** [review]

**Pull request merged**
